# Include the QtPyVCP default menubar.
{% include "default_menubar.yml" %}

qtdesigner:
  ui_file: ( windows.mainwindow.kwargs.ui_file )
  qss_file: ( application.kwargs.stylesheet )

vcp:
  name: MindOverCnc Mill
  version: v0.0.1
  author: Vasi Mihalca
  description: >
    Put a short description of your VCP here. This will be
    shown in the VCP Chooser when launching QtPyVCP with the
    --chooser option.


    Examples of what to included here:
      * VCP Features
      * Type of machine the VCP is for
      * Development status
      * Acknowledgments

data_plugins:
  status:
    kwargs:
      cycle_time: 15
  notifications:
    provider: qtpyvcp.plugins.notifications:Notifications
    kwargs:
      enabled: False    

windows:

  mainwindow:
    # Specify the class to use for the VCP's mainwindow
    #   Format: package.module:class
    provider: mindovercncmill.mainwindow:MyMainWindow

    # Keyword arguments to pass when initializing the class.
    kwargs:
      # Specify the mainwindow menubar as the default.
      menu: ( default_menubar )
      # Specify the UI file to load the window layout from.
      ui_file: {{ file.dir }}/ui/mainwindow.ui
      # Specify a stylesheet to use only for mainwindow.
      stylesheet: null
      # Set the window title from from the date in the vcp section above.
      title: ( vcp.name ) ( vcp.version)

dialogs:
  estop_pressed:
    provider: mindovercncmill.widgets.estop_overlay:EstopOverlay

  program_header:
    provider: mindovercncmill.widgets.program_header_overlay:ProgramHeaderOverlay

  facing_operation:
    provider: mindovercncmill.widgets.facing_op_overlay:FacingOpOverlay

application:
  kwargs:
    # Specify the application wide stylesheet.
    stylesheet: {{ file.dir }}/ui/style.qss

settings:
    
  probewizard.setting_probe_fast_fr:
    description: Fast-Probe Feed Rate
    default_value: 200.0
    persistent: true
    min_value: 0
    max_value: 9999

  probewizard.setting_probe_slow_fr:
    description: Slow-Probe Feed Rate
    default_value: 10.0
    persistent: true
    min_value: 0
    max_value: 9999    

  probewizard.setting_calibration_offset:
    description: Probe trigger point offset
    default_value: 0.0
    persistent: true
    min_value: 0
    max_value: 1

  probewizard.setting_probe_tool_number:
    description: Probe tool number
    default_value: 99
    persistent: true
    min_value: 0
    max_value: 9999

  probewizard.setting_latch_distance:
    description: Latch distance
    default_value: 0.5
    persistent: true
    min_value: 0.1
    max_value: 5.0  

  probewizard.setting_probe_mode:
    description: Probe Mode
    default_value: 0
    persistent: true
    min_value: 0
    max_value: 1   

  probewizard.input_step_off_width:
    description: probe step off width
    default_value: 10
    persistent: true
    min_value: 0
    max_value: 100

  probewizard.input_max_xy_distance:
    description: max x and y probe travel distance
    default_value: 12
    persistent: true
    min_value: 0
    max_value: 100

  probewizard.input_xy_clearance:
    description: x and y clearance distance
    default_value: 0.0
    persistent: true
    min_value: 0
    max_value: 1000

  probewizard.input_max_z_distance:
    description: max z probe travel distance
    default_value: 10.0
    persistent: true
    min_value: 0
    max_value: 100

  probewizard.input_z_final_retract:
    description: z final retract distance
    default_value: 0.5
    persistent: true
    min_value: 0.1
    max_value: 5.0  

  probewizard.input_extra_probe_depth:
    description: extra probe depth
    default_value: 0.0
    persistent: true
    min_value: 0
    max_value: 100

  probewizard.input_edge_width:
    description: edge width probing distance
    default_value: 10
    persistent: true
    min_value: 0
    max_value: 1000

  probewizard.input_diameter_hint:
    description: Aproximate diameter
    default_value: 0
    persistent: true
    min_value: 0
    max_value: 1000



  tool-setter-probe.x-coordinate:
    description: X position in machine coordinates
    default_value: 387
    persistent: true
    min_value: -1000
    max_value: 1000

  tool-setter-probe.y-coordinate:
    description: Y position in machine coordinates
    default_value: 218
    persistent: true
    min_value: -1000
    max_value: 1000  

  tool-setter-probe.z-coordinate:
    description: Z position where the search starts from - in machine coordinates
    default_value: -200
    persistent: true
    min_value: -1000
    max_value: 1000    

  tool-setter-probe.fast-probe-fr:
    description: tool probe fast feedrate.
    default_value: 500
    persistent: true
    min_value: 10
    max_value: 1000

  tool-setter-probe.slow-probe-fr:
    description: tool probe slow feedrate.
    default_value: 20
    persistent: true
    min_value: -10
    max_value: 1000

  tool-setter-probe.z-max-travel:
    description: maximumm z travel while probing before erroring out.
    default_value: -150
    persistent: true
    min_value: -1000
    max_value: 1000

  tool-setter-probe.retract-distance:
    description: distance tool retracts after fast probe move.
    default_value: 1
    persistent: true
    min_value: 0
    max_value: 10

  tool-setter-probe.spindle-nose-height:
    description: distance from home to tool setter for the spindle nose.
    default_value: 0.0
    persistent: true
    min_value: -1000
    max_value: 1000  
