# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'probe_wizard_widget.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1072, 610)
        self.stackedWidget = VCPStackedWidget(Form)
        self.stackedWidget.setGeometry(QtCore.QRect(30, 20, 1016, 586))
        self.stackedWidget.setStyleSheet("background: rgb(136, 138, 133)")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_loadProbeTool = QtWidgets.QWidget()
        self.page_loadProbeTool.setObjectName("page_loadProbeTool")
        self.label = QtWidgets.QLabel(self.page_loadProbeTool)
        self.label.setGeometry(QtCore.QRect(225, 95, 326, 61))
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.page_loadProbeTool)
        self.page_tripProbeTip = QtWidgets.QWidget()
        self.page_tripProbeTip.setObjectName("page_tripProbeTip")
        self.label_2 = QtWidgets.QLabel(self.page_tripProbeTip)
        self.label_2.setGeometry(QtCore.QRect(210, 170, 321, 56))
        self.label_2.setObjectName("label_2")
        self.label_7 = QtWidgets.QLabel(self.page_tripProbeTip)
        self.label_7.setGeometry(QtCore.QRect(320, 220, 101, 66))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/probe_icons/touch.png"))
        self.label_7.setObjectName("label_7")
        self.stackedWidget.addWidget(self.page_tripProbeTip)
        self.page_selectProbeOperation = QtWidgets.QWidget()
        self.page_selectProbeOperation.setObjectName("page_selectProbeOperation")
        self.gridLayoutWidget = QtWidgets.QWidget(self.page_selectProbeOperation)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(15, 15, 291, 276))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.probepushbutton = ProbePushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.probepushbutton.sizePolicy().hasHeightForWidth())
        self.probepushbutton.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/probe_icons/X+Y-.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.probepushbutton.setIcon(icon)
        self.probepushbutton.setIconSize(QtCore.QSize(75, 75))
        self.probepushbutton.setObjectName("probepushbutton")
        self.probeButtonGroup = QtWidgets.QButtonGroup(Form)
        self.probeButtonGroup.setObjectName("probeButtonGroup")
        self.probeButtonGroup.addButton(self.probepushbutton)
        self.gridLayout_3.addWidget(self.probepushbutton, 0, 0, 1, 1)
        self.probepushbutton_4 = ProbePushButton(self.gridLayoutWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/probe_icons/X+.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.probepushbutton_4.setIcon(icon1)
        self.probepushbutton_4.setIconSize(QtCore.QSize(75, 75))
        self.probepushbutton_4.setObjectName("probepushbutton_4")
        self.probeButtonGroup.addButton(self.probepushbutton_4)
        self.gridLayout_3.addWidget(self.probepushbutton_4, 1, 0, 1, 1)
        self.probepushbutton_2 = ProbePushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.probepushbutton_2.sizePolicy().hasHeightForWidth())
        self.probepushbutton_2.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/probe_icons/inY-.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.probepushbutton_2.setIcon(icon2)
        self.probepushbutton_2.setIconSize(QtCore.QSize(75, 75))
        self.probepushbutton_2.setObjectName("probepushbutton_2")
        self.probeButtonGroup.addButton(self.probepushbutton_2)
        self.gridLayout_3.addWidget(self.probepushbutton_2, 0, 1, 1, 1)
        self.probepushbutton_3 = ProbePushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.probepushbutton_3.sizePolicy().hasHeightForWidth())
        self.probepushbutton_3.setSizePolicy(sizePolicy)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/probe_icons/X-Y-.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.probepushbutton_3.setIcon(icon3)
        self.probepushbutton_3.setIconSize(QtCore.QSize(75, 75))
        self.probepushbutton_3.setObjectName("probepushbutton_3")
        self.probeButtonGroup.addButton(self.probepushbutton_3)
        self.gridLayout_3.addWidget(self.probepushbutton_3, 0, 2, 1, 1)
        self.probepushbutton_5 = ProbePushButton(self.gridLayoutWidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/probe_icons/X+Y+.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.probepushbutton_5.setIcon(icon4)
        self.probepushbutton_5.setIconSize(QtCore.QSize(75, 75))
        self.probepushbutton_5.setObjectName("probepushbutton_5")
        self.probeButtonGroup.addButton(self.probepushbutton_5)
        self.gridLayout_3.addWidget(self.probepushbutton_5, 2, 0, 1, 1)
        self.probepushbutton_6 = ProbePushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.probepushbutton_6.sizePolicy().hasHeightForWidth())
        self.probepushbutton_6.setSizePolicy(sizePolicy)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/probe_icons/Y+.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.probepushbutton_6.setIcon(icon5)
        self.probepushbutton_6.setIconSize(QtCore.QSize(75, 75))
        self.probepushbutton_6.setObjectName("probepushbutton_6")
        self.probeButtonGroup.addButton(self.probepushbutton_6)
        self.gridLayout_3.addWidget(self.probepushbutton_6, 2, 1, 1, 1)
        self.probepushbutton_7 = ProbePushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.probepushbutton_7.sizePolicy().hasHeightForWidth())
        self.probepushbutton_7.setSizePolicy(sizePolicy)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/probe_icons/X-Y+.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.probepushbutton_7.setIcon(icon6)
        self.probepushbutton_7.setIconSize(QtCore.QSize(75, 75))
        self.probepushbutton_7.setObjectName("probepushbutton_7")
        self.probeButtonGroup.addButton(self.probepushbutton_7)
        self.gridLayout_3.addWidget(self.probepushbutton_7, 2, 2, 1, 1)
        self.probepushbutton_8 = ProbePushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.probepushbutton_8.sizePolicy().hasHeightForWidth())
        self.probepushbutton_8.setSizePolicy(sizePolicy)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/probe_icons/X-.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.probepushbutton_8.setIcon(icon7)
        self.probepushbutton_8.setIconSize(QtCore.QSize(75, 75))
        self.probepushbutton_8.setObjectName("probepushbutton_8")
        self.probeButtonGroup.addButton(self.probepushbutton_8)
        self.gridLayout_3.addWidget(self.probepushbutton_8, 1, 2, 1, 1)
        self.probepushbutton_17 = ProbePushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.probepushbutton_17.sizePolicy().hasHeightForWidth())
        self.probepushbutton_17.setSizePolicy(sizePolicy)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/probe_icons/down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.probepushbutton_17.setIcon(icon8)
        self.probepushbutton_17.setIconSize(QtCore.QSize(75, 75))
        self.probepushbutton_17.setObjectName("probepushbutton_17")
        self.probeButtonGroup.addButton(self.probepushbutton_17)
        self.gridLayout_3.addWidget(self.probepushbutton_17, 1, 1, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.page_selectProbeOperation)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(420, 15, 291, 276))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.probepushbutton_9 = ProbePushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.probepushbutton_9.sizePolicy().hasHeightForWidth())
        self.probepushbutton_9.setSizePolicy(sizePolicy)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/probe_icons/inX-Y+.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.probepushbutton_9.setIcon(icon9)
        self.probepushbutton_9.setIconSize(QtCore.QSize(75, 75))
        self.probepushbutton_9.setObjectName("probepushbutton_9")
        self.probeButtonGroup.addButton(self.probepushbutton_9)
        self.gridLayout_5.addWidget(self.probepushbutton_9, 0, 0, 1, 1)
        self.probepushbutton_10 = ProbePushButton(self.gridLayoutWidget_2)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/probe_icons/inX-.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.probepushbutton_10.setIcon(icon10)
        self.probepushbutton_10.setIconSize(QtCore.QSize(75, 75))
        self.probepushbutton_10.setObjectName("probepushbutton_10")
        self.probeButtonGroup.addButton(self.probepushbutton_10)
        self.gridLayout_5.addWidget(self.probepushbutton_10, 1, 0, 1, 1)
        self.probepushbutton_11 = ProbePushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.probepushbutton_11.sizePolicy().hasHeightForWidth())
        self.probepushbutton_11.setSizePolicy(sizePolicy)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/probe_icons/inY+.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.probepushbutton_11.setIcon(icon11)
        self.probepushbutton_11.setIconSize(QtCore.QSize(75, 75))
        self.probepushbutton_11.setObjectName("probepushbutton_11")
        self.probeButtonGroup.addButton(self.probepushbutton_11)
        self.gridLayout_5.addWidget(self.probepushbutton_11, 0, 1, 1, 1)
        self.probepushbutton_12 = ProbePushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.probepushbutton_12.sizePolicy().hasHeightForWidth())
        self.probepushbutton_12.setSizePolicy(sizePolicy)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/probe_icons/inX+Y+.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.probepushbutton_12.setIcon(icon12)
        self.probepushbutton_12.setIconSize(QtCore.QSize(75, 75))
        self.probepushbutton_12.setObjectName("probepushbutton_12")
        self.probeButtonGroup.addButton(self.probepushbutton_12)
        self.gridLayout_5.addWidget(self.probepushbutton_12, 0, 2, 1, 1)
        self.probepushbutton_13 = ProbePushButton(self.gridLayoutWidget_2)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/probe_icons/inX-Y-.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.probepushbutton_13.setIcon(icon13)
        self.probepushbutton_13.setIconSize(QtCore.QSize(75, 75))
        self.probepushbutton_13.setObjectName("probepushbutton_13")
        self.probeButtonGroup.addButton(self.probepushbutton_13)
        self.gridLayout_5.addWidget(self.probepushbutton_13, 2, 0, 1, 1)
        self.probepushbutton_14 = ProbePushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.probepushbutton_14.sizePolicy().hasHeightForWidth())
        self.probepushbutton_14.setSizePolicy(sizePolicy)
        self.probepushbutton_14.setIcon(icon2)
        self.probepushbutton_14.setIconSize(QtCore.QSize(75, 75))
        self.probepushbutton_14.setObjectName("probepushbutton_14")
        self.probeButtonGroup.addButton(self.probepushbutton_14)
        self.gridLayout_5.addWidget(self.probepushbutton_14, 2, 1, 1, 1)
        self.probepushbutton_15 = ProbePushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.probepushbutton_15.sizePolicy().hasHeightForWidth())
        self.probepushbutton_15.setSizePolicy(sizePolicy)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/probe_icons/inX+Y-.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.probepushbutton_15.setIcon(icon14)
        self.probepushbutton_15.setIconSize(QtCore.QSize(75, 75))
        self.probepushbutton_15.setObjectName("probepushbutton_15")
        self.probeButtonGroup.addButton(self.probepushbutton_15)
        self.gridLayout_5.addWidget(self.probepushbutton_15, 2, 2, 1, 1)
        self.probepushbutton_16 = ProbePushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.probepushbutton_16.sizePolicy().hasHeightForWidth())
        self.probepushbutton_16.setSizePolicy(sizePolicy)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/probe_icons/inX+.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.probepushbutton_16.setIcon(icon15)
        self.probepushbutton_16.setIconSize(QtCore.QSize(75, 75))
        self.probepushbutton_16.setObjectName("probepushbutton_16")
        self.probeButtonGroup.addButton(self.probepushbutton_16)
        self.gridLayout_5.addWidget(self.probepushbutton_16, 1, 2, 1, 1)
        self.probepushbutton_18 = ProbePushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.probepushbutton_18.sizePolicy().hasHeightForWidth())
        self.probepushbutton_18.setSizePolicy(sizePolicy)
        self.probepushbutton_18.setIcon(icon8)
        self.probepushbutton_18.setIconSize(QtCore.QSize(75, 75))
        self.probepushbutton_18.setObjectName("probepushbutton_18")
        self.probeButtonGroup.addButton(self.probepushbutton_18)
        self.gridLayout_5.addWidget(self.probepushbutton_18, 1, 1, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.page_selectProbeOperation)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(190, 365, 174, 166))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.probepushbutton_28 = ProbePushButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.probepushbutton_28.sizePolicy().hasHeightForWidth())
        self.probepushbutton_28.setSizePolicy(sizePolicy)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/probe_icons/angleX+.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.probepushbutton_28.setIcon(icon16)
        self.probepushbutton_28.setIconSize(QtCore.QSize(75, 75))
        self.probepushbutton_28.setObjectName("probepushbutton_28")
        self.probeButtonGroup.addButton(self.probepushbutton_28)
        self.gridLayout_7.addWidget(self.probepushbutton_28, 0, 0, 1, 1)
        self.probepushbutton_29 = ProbePushButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.probepushbutton_29.sizePolicy().hasHeightForWidth())
        self.probepushbutton_29.setSizePolicy(sizePolicy)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/probe_icons/angleY+.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.probepushbutton_29.setIcon(icon17)
        self.probepushbutton_29.setIconSize(QtCore.QSize(75, 75))
        self.probepushbutton_29.setObjectName("probepushbutton_29")
        self.probeButtonGroup.addButton(self.probepushbutton_29)
        self.gridLayout_7.addWidget(self.probepushbutton_29, 1, 0, 1, 1)
        self.probepushbutton_30 = ProbePushButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.probepushbutton_30.sizePolicy().hasHeightForWidth())
        self.probepushbutton_30.setSizePolicy(sizePolicy)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/probe_icons/angleY-.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.probepushbutton_30.setIcon(icon18)
        self.probepushbutton_30.setIconSize(QtCore.QSize(75, 75))
        self.probepushbutton_30.setObjectName("probepushbutton_30")
        self.probeButtonGroup.addButton(self.probepushbutton_30)
        self.gridLayout_7.addWidget(self.probepushbutton_30, 0, 1, 1, 1)
        self.probepushbutton_31 = ProbePushButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.probepushbutton_31.sizePolicy().hasHeightForWidth())
        self.probepushbutton_31.setSizePolicy(sizePolicy)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/probe_icons/angleX-.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.probepushbutton_31.setIcon(icon19)
        self.probepushbutton_31.setIconSize(QtCore.QSize(75, 75))
        self.probepushbutton_31.setObjectName("probepushbutton_31")
        self.probeButtonGroup.addButton(self.probepushbutton_31)
        self.gridLayout_7.addWidget(self.probepushbutton_31, 1, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_selectProbeOperation)
        self.page_enterParameters = QtWidgets.QWidget()
        self.page_enterParameters.setObjectName("page_enterParameters")
        self.buttonChangeRoutine = QtWidgets.QPushButton(self.page_enterParameters)
        self.buttonChangeRoutine.setGeometry(QtCore.QRect(90, 35, 171, 36))
        self.buttonChangeRoutine.setObjectName("buttonChangeRoutine")
        self.labelSelectedRoutine = QtWidgets.QLabel(self.page_enterParameters)
        self.labelSelectedRoutine.setGeometry(QtCore.QRect(20, 85, 316, 26))
        self.labelSelectedRoutine.setObjectName("labelSelectedRoutine")
        self.buttonGenerateCode = QtWidgets.QPushButton(self.page_enterParameters)
        self.buttonGenerateCode.setGeometry(QtCore.QRect(250, 505, 196, 46))
        self.buttonGenerateCode.setObjectName("buttonGenerateCode")
        self.labelResult = QtWidgets.QLabel(self.page_enterParameters)
        self.labelResult.setGeometry(QtCore.QRect(465, 485, 486, 86))
        self.labelResult.setFrameShape(QtWidgets.QFrame.Box)
        self.labelResult.setObjectName("labelResult")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.page_enterParameters)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(375, 75, 326, 276))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        self.pushButton = QtWidgets.QPushButton(self.page_enterParameters)
        self.pushButton.setGeometry(QtCore.QRect(80, 505, 106, 41))
        self.pushButton.setObjectName("pushButton")
        self.settings_lineedit = VCPSettingsLineEdit(self.page_enterParameters)
        self.settings_lineedit.setGeometry(QtCore.QRect(60, 185, 142, 25))
        self.settings_lineedit.setObjectName("settings_lineedit")
        self.stackedWidget.addWidget(self.page_enterParameters)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Load the probe tool into the spindle\n"
"and plug the cable"))
        self.label_2.setText(_translate("Form", "Touch the tip of the probe to ensure its working"))
        self.probepushbutton.setProperty("filename", _translate("Form", "probe_back_left_corner.ngc"))
        self.probepushbutton_4.setProperty("filename", _translate("Form", "probe_x_plus.ngc"))
        self.probepushbutton_2.setProperty("filename", _translate("Form", "probe_y_minus.ngc"))
        self.probepushbutton_17.setProperty("filename", _translate("Form", "probe_z_minus.ngc"))
        self.buttonChangeRoutine.setText(_translate("Form", "Change Routine"))
        self.labelSelectedRoutine.setText(_translate("Form", "Selected Routine Name"))
        self.buttonGenerateCode.setText(_translate("Form", "Generate Probing Code"))
        self.labelResult.setText(_translate("Form", "TextLabel"))
        self.radioButton.setText(_translate("Form", "RadioButton"))
        self.pushButton.setText(_translate("Form", "PushButton"))
        self.settings_lineedit.setProperty("settingName", _translate("Form", "probe-input.input_probe_fast_fr"))

from qtpyvcp.widgets.containers.stack import VCPStackedWidget
from qtpyvcp.widgets.input_widgets.setting_slider import VCPSettingsLineEdit
from widgets.probe_push_button import ProbePushButton
import resources_rc
